source 'https://rubygems.org'
gem 'sqlite3', '~> 1.3.4'
gem 'cucumber', '~> 1.0.6'
# gem 'cucumber-rails', '~> 1.0.6'
gem "rspec", "2.8.0"
gem 'rspec-rails'
gem 'rails', '~> 3.0'

if RUBY_VERSION =~ /^2\.0|^1\.9/
  gem 'debugger'
else
  gem 'ruby-debug'
end
gem 'spork', :github => 'sporkrb/spork', :branch => 'modernize-wip'
gem 'spork-rails', :path => "../../../"
