source :gemcutter
gem 'sqlite3', '~> 1.3.4'
gem 'cucumber', '~> 1.0.6'
# gem 'cucumber-rails', '~> 1.0.6'
gem "rspec", "2.8.0"
gem 'rspec-rails'
gem 'rails', '~> 3.0.7'

if RUBY_VERSION =~ /^1\.9/
  gem 'ruby-debug19'
else
  gem 'ruby-debug', '>= 0.10.3'
end
gem 'spork', "~> 1.0.0rc0"
gem 'spork-rails', :path => "../../../"
