source 'https://rubygems.org'
gem 'sqlite3', '~> 1.3.7'
gem 'cucumber', '~> 1.3.2'
gem 'rspec', '~> 2.13.0'
gem 'rspec-rails', '~> 2.13.2'
gem 'rails', '~> 4.0'
gem 'jquery-rails'
gem 'turbolinks'

if RUBY_VERSION =~ /^2\.0|^1\.9/
  gem 'debugger'
else
  gem 'ruby-debug'
end
gem 'spork', '>= 1.0rc0'
gem 'spork-rails', :path => "../../../"
